var annotated_dup =
[
    [ "ActiveBMSArray", "class_active_b_m_s_array.html", "class_active_b_m_s_array" ],
    [ "ActiveBMSBoard", "class_active_b_m_s_board.html", "class_active_b_m_s_board" ],
    [ "Application", "class_application.html", "class_application" ],
    [ "BelDCDCConverter", "class_bel_d_c_d_c_converter.html", "class_bel_d_c_d_c_converter" ],
    [ "BMS1000M", "class_b_m_s1000_m.html", "class_b_m_s1000_m" ],
    [ "BMSMonitor", "class_b_m_s_monitor.html", "class_b_m_s_monitor" ],
    [ "BMSMonitorArray", "class_b_m_s_monitor_array.html", "class_b_m_s_monitor_array" ],
    [ "CAB300", "class_c_a_b300.html", "class_c_a_b300" ],
    [ "CANInterface", "class_c_a_n_interface.html", "class_c_a_n_interface" ],
    [ "CANReceiver", "class_c_a_n_receiver.html", "class_c_a_n_receiver" ],
    [ "CANSystem", "class_c_a_n_system.html", "class_c_a_n_system" ],
    [ "CurrentWaysCharger", "class_current_ways_charger.html", "class_current_ways_charger" ],
    [ "DelphiU2C", "class_delphi_u2_c.html", "class_delphi_u2_c" ],
    [ "EltekCharger", "class_eltek_charger.html", "class_eltek_charger" ],
    [ "FaultManager", "class_fault_manager.html", "class_fault_manager" ],
    [ "MMC4000", "class_m_m_c4000.html", "class_m_m_c4000" ],
    [ "Pin", "class_pin.html", "class_pin" ],
    [ "RMSFastCharger", "class_r_m_s_fast_charger.html", "class_r_m_s_fast_charger" ],
    [ "RMSInverter", "class_r_m_s_inverter.html", "class_r_m_s_inverter" ],
    [ "tCANBitClkParms", "structt_c_a_n_bit_clk_parms.html", "structt_c_a_n_bit_clk_parms" ],
    [ "tCANMsgObject", "structt_c_a_n_msg_object.html", "structt_c_a_n_msg_object" ],
    [ "tDMAControlTable", "structt_d_m_a_control_table.html", "structt_d_m_a_control_table" ],
    [ "tEMACDES3", "uniont_e_m_a_c_d_e_s3.html", "uniont_e_m_a_c_d_e_s3" ],
    [ "tEMACDMADescriptor", "structt_e_m_a_c_d_m_a_descriptor.html", "structt_e_m_a_c_d_m_a_descriptor" ],
    [ "tEMACWakeUpFrameFilter", "structt_e_m_a_c_wake_up_frame_filter.html", "structt_e_m_a_c_wake_up_frame_filter" ],
    [ "TivaPin", "class_tiva_pin.html", "class_tiva_pin" ],
    [ "tLCDIDDTiming", "structt_l_c_d_i_d_d_timing.html", "structt_l_c_d_i_d_d_timing" ],
    [ "tLCDRasterTiming", "structt_l_c_d_raster_timing.html", "structt_l_c_d_raster_timing" ],
    [ "VCU1200_Board", "class_v_c_u1200___board.html", "class_v_c_u1200___board" ]
];